export function setPreferences(mobile) {
  if (!mobile) {
    const preferences = {
      dimensions: {
        textFontSize: "10px",
        textSubTitleSize: "12px",
        textTitleSize: "15px",
        maxLinesHeight: "50px",
        maxLinesPadding: "20px",
        mediumLinesPadding: "10px",
        maxBorderHeight: "6px",
        mediumBorderHeight: "4px",
        minimumBorderHeight: "2px",
        maxCloseSidebarWidth: "100px",
        minCloseSidebarWidth: "80px",
        maxOpenSidebarWidth: "350px",
        minOpenSidebarWidth: "300px",
        sidebarPadding: "7px",
        homeTextContent: "800px",
        paddingHomeTextContent: "10px",
        marginHomeTextContent: "15px",
        titlePageFontSize: "35px",
        titlePagePadding: "15px",
        titlePageMargin: "15px",
        subTitlePageMargin: "20px",
        subTitlePadding: "15px",
        listOfButtonsPadding: "10px",
        grandHeightToDiv: "500px",
        mediumHeightToDiv: "300px",
        smallHeightToDiv: "30px",
        smallWidthToDiv: "150px",
        mediumWidthToDiv: "300px",
        grandWidthToDiv: "650px",
        maxTableWidth: "1200px",
        defaultDivMargin: "10px",
        defaultDivPadding: "10px",
        smallDivPadding: "7px",
        grandDivPadding: "15px",
        smallTextAreaHeight: "100px",
      },
    };

    return preferences;
  } else {
    const preferences = {
      dimensions: {
        textFontSize: "4px",
        textSubTitleSize: "12px",
        textTitleSize: "8px",
        maxLinesHeight: "20px",
        maxLinesPadding: "7px",
        mediumLinesPadding: "4px",
        maxBorderHeight: "3px",
        mediumBorderHeight: "2px",
        minimumBorderHeight: "1px",
        maxCloseSidebarWidth: "75px",
        minCloseSidebarWidth: "40px",
        maxOpenSidebarWidth: "175px",
        minOpenSidebarWidth: "150px",
        sidebarPadding: "3px",
        homeTextContent: "225px",
        paddingHomeTextContent: "7px",
        marginHomeTextContent: "5px",
        titlePageFontSize: "20px",
        titlePagePadding: "7px",
        titlePageMargin: "7px",
        subTitlePageMargin: "10px",
        subTitlePadding: "7px",
        listOfButtonsPadding: "7px",
        grandHeightToDiv: "500px",
        mediumHeightToDiv: "300px",
        mediumWidthToDiv: "300px",
        grandWidthToDiv: "250px",
        defaultDivMargin: "10px",
        defaultDivPadding: "10px",
        smallDivPadding: "7px",
        grandDivPadding: "15px",
      },
    };
    return preferences;
  }
}
