export default function styles(isMobile) {
  const style = {
    background: {
      width: "100vw",
      height: "100vh",
      boxSizing: "border-box",
      display: "flex",
      flexDirection: "column",
      backgroundColor: "#4C61A7",
      color: "white",
      overflow: "hidden",
    },
    header: {
      width: "100%",
      height: "50px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "#061242",
      flexShrink: 0,
    },
    contents: {
      flex: 1,
      width: "100%",
      display: "flex",
      flexDirection: "row",
      overflow: "hidden",
    },
    sidebar: {
      width: isMobile ? "50px" : "200px",
      height: "100%",
      backgroundColor: "#061242",
      display: "flex",
      flexDirection: "column",
      boxSizing: "border-box",
      overflowY: "auto",
    },
    backgroundImage: {
      flexGrow: 1,
      height: "100%",
      boxSizing: "border-box",
      display: "flex",
      flexDirection: "column",
      overflow: "auto",
      justifyContent: "center",
      alignItems: "center",
      padding: "20px",
      backgroundImage: "url('/images/background/model6.png')",
      backgroundSize: "cover",
      backgroundPosition: "center",
      backgroundRepeat: "no-repeat",
    },
    sidebarItem: {
      width: "100%",
      cursor: "pointer",
      textAlign: "center",
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      gap: isMobile ? "0px" : "10px",
      paddingLeft: isMobile ? "0px" : "10px",
      boxSizing: "border-box",
      justifyContent: "left",
    },
    translucedContainer: {
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      borderRadius: "10px",
      padding: isMobile ? "10px" : "20px",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
      width: "100%",
      height: "100%",
      boxSizing: "border-box",
      textAlign: "center",
      display: "flex",
      gap: isMobile ? "10px" : "20px",
      flexWrap: "wrap",
    },
    translucedBox: {
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      borderRadius: "10px",
      padding: isMobile ? "10px" : "20px",
      boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
      marginBottom: "20px",
      height: isMobile ? "auto" : "60px",
      width: "auto",
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
    },
    title: {
      width: "100%",
      height: "40px",
      fontSize: isMobile ? "18px" : "24px",
      fontWeight: "bold",
      backgroundColor: "rgba(0, 0, 0, 0.6)",
      textAlign: "center",
      display: "flex",
      justifyContent: "center",
      padding: isMobile ? "10px" : "20px",
    },
    toggleSwitch: (isOn) => ({
      width: "50px",
      height: "25px",
      borderRadius: "25px",
      backgroundColor: isOn ? "#4CAF50" : "#999",
      display: "flex",
      alignItems: "center",
      padding: "3px",
      cursor: "pointer",
      transition: "background-color 0.3s",
    }),
    toggleKnob: (isOn) => ({
      width: "20px",
      height: "20px",
      borderRadius: "50%",
      backgroundColor: "white",
      transform: isOn ? "translateX(25px)" : "translateX(0)",
      transition: "transform 0.3s",
    }),
    table: {
      width: "100%",
      borderCollapse: "collapse",
      color: "white",
    },
    th: {
      backgroundColor: "#061242",
      color: "#FFFFFF",
      padding: isMobile ? "8px" : "12px",
      textAlign: "center",
      fontWeight: "bold",
      borderBottom: "2px solid #FBA24D",
      whiteSpace: "nowrap",
    },
    td: {
      padding: isMobile ? "8px" : "10px",
      height: "40px",
      borderBottom: "1px solid #4C61A7",
    },
    trOdd: {
      backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    trEven: {
      backgroundColor: "rgba(0, 0, 0, 0.1)",
    },
    tableInput: {
      width: "100%",
      padding: "8px",
      boxSizing: "border-box",
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      color: "white",
      border: "1px solid #4C61A7",
      borderRadius: "4px",
      fontFamily: "'Montserrat', sans-serif",
    },
    tableSelect: {
      width: "100%",
      padding: "8px",
      boxSizing: "border-box",
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      color: "white",
      border: "1px solid #4C61A7",
      borderRadius: "4px",
      fontFamily: "'Montserrat', sans-serif",
    },
    tableOption: {
      backgroundColor: "#061242",
      color: "white",
    },
    inputFile: {
      width: "100%",
      padding: "8px",
      boxSizing: "border-box",
      backgroundColor: "rgba(0, 0, 0, 0.4)",
      color: "white",
      border: "1px solid #4C61A7",
      borderRadius: "4px",
      fontFamily: "'Montserrat', sans-serif",
      cursor: "pointer",
    },
  };
  return style;
}
